sudo: required

language: ruby

addons:
  chrome: stable

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script: bundle exec rspec

env:
  matrix:
    - RAILS=5.1.6 AA=1.1.0
    - RAILS=5.2.1 AA=1.4.0
    - RAILS=5.2.2 AA=2.8.0
    - RAILS=6.0.0 AA=2.8.0

rvm:
  - 2.5
  - 2.6
